# Generated by Django 3.2.1 on 2022-09-21 03:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('localizacion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clasificadores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True)),
                ('fecha_baja', models.DateTimeField(blank=True, editable=False, null=True)),
                ('activo', models.BooleanField(default=True, editable=False, verbose_name='Activo')),
                ('titulo', models.CharField(max_length=200, unique=True, verbose_name='Titulo')),
                ('usuario_modificacion', models.IntegerField(blank=True, editable=False, null=True)),
                ('usuario_baja', models.IntegerField(blank=True, editable=False, null=True)),
                ('electrodependientes', models.BooleanField(choices=[(True, 'SI'), (False, 'NO')], default=False)),
            ],
            options={
                'verbose_name': 'Articulo',
                'verbose_name_plural': ' Articulos',
                'db_table': 'articulo',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True)),
                ('fecha_baja', models.DateTimeField(blank=True, editable=False, null=True)),
                ('activo', models.BooleanField(default=True, editable=False, verbose_name='Activo')),
                ('titulo', models.CharField(max_length=200, unique=True, verbose_name='Titulo')),
                ('usuario_modificacion', models.IntegerField(blank=True, editable=False, null=True)),
                ('usuario_baja', models.IntegerField(blank=True, editable=False, null=True)),
                ('usuario_creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'db_table': 'producto_categoria',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True)),
                ('fecha_baja', models.DateTimeField(blank=True, editable=False, null=True)),
                ('activo', models.BooleanField(default=True, editable=False, verbose_name='Activo')),
                ('titulo', models.CharField(max_length=200, unique=True, verbose_name='Titulo')),
                ('usuario_modificacion', models.IntegerField(blank=True, editable=False, null=True)),
                ('usuario_baja', models.IntegerField(blank=True, editable=False, null=True)),
                ('usuario_creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': ' Marcas',
                'db_table': 'producto_marca',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Subcategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True)),
                ('fecha_baja', models.DateTimeField(blank=True, editable=False, null=True)),
                ('activo', models.BooleanField(default=True, editable=False, verbose_name='Activo')),
                ('titulo', models.CharField(max_length=200, unique=True, verbose_name='Titulo')),
                ('usuario_modificacion', models.IntegerField(blank=True, editable=False, null=True)),
                ('usuario_baja', models.IntegerField(blank=True, editable=False, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.categoria')),
                ('usuario_creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Subcategoria',
                'verbose_name_plural': 'Subcategorias',
                'db_table': 'producto_subcategoria',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.IntegerField()),
                ('numero_serie', models.CharField(max_length=15, verbose_name='Numero de serie')),
                ('estado', models.CharField(max_length=20, verbose_name='Estado de uso')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor monetario')),
                ('situacion', models.CharField(choices=[('DISP', 'Disponible'), ('OTO', 'Otorgado'), ('NO_DISP', 'No disponible')], max_length=10, verbose_name='Situación del producto')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.articulo')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.marca')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='localizacion.pais', verbose_name='País de origen')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clasificadores.sucursal')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': '  Productos',
                'db_table': 'productos',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='articulo',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.categoria'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='subcategoria',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='categoria', chained_model_field='categoria', on_delete=django.db.models.deletion.CASCADE, to='productos.subcategoria'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='usuario_creador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
