# Generated by Django 3.2.1 on 2022-09-29 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='numero_serie',
            field=models.CharField(max_length=15, unique=True, verbose_name='Numero de serie'),
        ),
    ]
