# Generated by Django 4.0.4 on 2023-02-14 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('productos', '0003_alter_articulo_electrodependientes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoBaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo_baja', models.CharField(max_length=30, verbose_name='Motivo de baja')),
                ('fecha_baja', models.DateField(verbose_name='Fecha de baja')),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
                ('usuario_baja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
