# Generated by Django 4.0.1 on 2022-10-19 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clasificadores', '0002_alter_tipovivienda_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObraSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True)),
                ('fecha_baja', models.DateTimeField(blank=True, editable=False, null=True)),
                ('activo', models.BooleanField(default=True, editable=False, verbose_name='Activo')),
                ('titulo', models.CharField(max_length=200, unique=True, verbose_name='Titulo')),
                ('usuario_modificacion', models.IntegerField(blank=True, editable=False, null=True)),
                ('usuario_baja', models.IntegerField(blank=True, editable=False, null=True)),
                ('usuario_creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Obra social',
                'verbose_name_plural': 'Obras sociales',
                'db_table': 'obra_social',
                'ordering': ['id'],
            },
        ),
    ]
