# Generated by Django 4.0.4 on 2023-02-13 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('localizacion', '0002_alter_pais_codigo_alfa2_alter_pais_codigo_alfa3_and_more'),
        ('clasificadores', '0004_tipobaja'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='pais',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='localizacion.pais', verbose_name='Pais'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empresa',
            name='localidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='localizacion.localidad', verbose_name='Localidad'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='provincia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='localizacion.provincia', verbose_name='Provincia'),
        ),
    ]
