# Generated by Django 4.0.4 on 2023-02-13 13:22

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('localizacion', '0002_alter_pais_codigo_alfa2_alter_pais_codigo_alfa3_and_more'),
        ('clasificadores', '0005_empresa_pais_alter_empresa_localidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='localidad',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='provincia', chained_model_field='provincia', null=True, on_delete=django.db.models.deletion.CASCADE, to='localizacion.localidad'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='provincia',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='pais', chained_model_field='pais', null=True, on_delete=django.db.models.deletion.CASCADE, to='localizacion.provincia'),
        ),
    ]
