# Generated by Django 4.0.4 on 2023-02-14 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clasificadores', '0006_alter_empresa_localidad_alter_empresa_provincia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='puntoventa',
            options={'ordering': ['id'], 'verbose_name': 'Punto de prestamo', 'verbose_name_plural': ' Puntos de prestamo'},
        ),
    ]
