# Generated by Django 4.0.4 on 2023-03-20 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clasificadores', '0007_alter_puntoventa_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='codigo_area_c',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Cód. de área celular'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail de contacto'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='ingresos_brutos',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Ingresos Brutos'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='numero_telefono_c',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Nro. de celular'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='razon_social',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Razón Social'),
        ),
    ]
