# Generated by Django 3.2.1 on 2022-09-21 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre de País')),
                ('codigo_alfa2', models.CharField(max_length=2, verbose_name='Código Alfa 2')),
                ('codigo_alfa3', models.CharField(max_length=3, verbose_name='Código Alfa 3')),
                ('codigo_numerico', models.IntegerField(verbose_name='Código Numérico')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(blank=True, default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': '  Paises',
                'db_table': 'pais',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre de Provincia')),
                ('codigo', models.CharField(max_length=4, verbose_name='Código de Provincia')),
                ('region', models.IntegerField(choices=[(0, 'ESTE'), (1, 'OESTE'), (2, 'NORTE'), (3, 'SUR'), (4, 'NORESTE'), (5, 'SURESTE'), (6, 'NOROESTE'), (7, 'SUROESTE'), (8, 'CENTRO'), (9, 'CENTROESTE'), (10, 'CENTROOESTE'), (11, 'CENTRONORTE'), (12, 'CENTROSUR')], verbose_name='Zona Geográfica:')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(blank=True, default=True, verbose_name='Activo')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='localizacion.pais')),
            ],
            options={
                'verbose_name': 'Provincia',
                'verbose_name_plural': '  Provincias',
                'db_table': 'provincia',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_postal', models.CharField(max_length=6, verbose_name='Código Postal')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre')),
                ('zona', models.IntegerField(choices=[(0, 'Centro'), (1, 'Norte'), (2, 'Sur')], verbose_name='Zona')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(blank=True, default=True, verbose_name='Activa')),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='localizacion.provincia')),
            ],
            options={
                'verbose_name': 'Localidad',
                'verbose_name_plural': ' Localidades',
                'db_table': 'localidad',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Barrio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('zona', models.IntegerField(choices=[(0, 'Urbana'), (1, 'Rural')], verbose_name='Zona')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(blank=True, default=True, verbose_name='Activo')),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='localizacion.localidad')),
            ],
            options={
                'verbose_name': 'Barrio',
                'verbose_name_plural': 'Barrios',
                'db_table': 'barrio',
                'ordering': ['nombre'],
            },
        ),
    ]
