# Generated by Django 4.0.4 on 2023-02-13 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localizacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pais',
            name='codigo_alfa2',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Código Alfa 2'),
        ),
        migrations.AlterField(
            model_name='pais',
            name='codigo_alfa3',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Código Alfa 3'),
        ),
        migrations.AlterField(
            model_name='pais',
            name='codigo_numerico',
            field=models.IntegerField(blank=True, null=True, verbose_name='Código Numérico'),
        ),
    ]
