# Generated by Django 4.0.1 on 2022-09-30 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clasificadores', '0002_alter_tipovivienda_options'),
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='beneficiario',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='beneficiario',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='beneficiario', to='persona.persona', verbose_name='Beneficiario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='discapacidad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clasificadores.tipodiscapacidad', verbose_name='Discapadidad'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='responsable',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='responsable', to='persona.persona', verbose_name='Responsable'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Responsable',
        ),
        migrations.RemoveField(
            model_name='beneficiario',
            name='persona',
        ),
    ]
