# Generated by Django 4.0.1 on 2022-09-30 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('persona', '0002_alter_beneficiario_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiario',
            name='activo',
            field=models.BooleanField(default=True, editable=False, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='fecha_baja',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='usuario_baja',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='usuario_creador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='usuario_modificacion',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
