# Generated by Django 4.0.1 on 2022-09-30 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0003_beneficiario_activo_beneficiario_fecha_baja_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiario',
            name='responsable',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='responsable', to='persona.persona', verbose_name='Responsable'),
        ),
    ]
