# Generated by Django 4.0.1 on 2022-10-03 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0004_alter_beneficiario_responsable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentacionbeneficiario',
            name='vencimiento',
            field=models.BooleanField(blank=True, choices=[(True, 'SI'), (False, 'NO')], null=True, verbose_name='¿Tiene vencimiento?'),
        ),
    ]
