# Generated by Django 4.0.1 on 2022-10-03 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0005_alter_documentacionbeneficiario_vencimiento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beneficiario',
            old_name='beneficiario',
            new_name='persona_beneficiaria',
        ),
        migrations.RenameField(
            model_name='beneficiario',
            old_name='responsable',
            new_name='persona_responsable',
        ),
        migrations.AlterField(
            model_name='documentacionbeneficiario',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de vencimiento'),
        ),
    ]
