# Generated by Django 4.0.1 on 2022-10-03 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clasificadores', '0002_alter_tipovivienda_options'),
        ('persona', '0007_alter_documentacionbeneficiario_beneficiario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentacionbeneficiario',
            name='archivo',
            field=models.ImageField(upload_to='documentacion', verbose_name='Adjuntar documentación'),
        ),
        migrations.AlterField(
            model_name='documentacionbeneficiario',
            name='tipo_documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clasificadores.tipodocumento', verbose_name='Documentación'),
        ),
    ]
