# Generated by Django 4.0.1 on 2022-10-19 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clasificadores', '0003_obrasocial'),
        ('persona', '0008_alter_documentacionbeneficiario_archivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiario',
            name='archivo_cud',
            field=models.ImageField(blank=True, null=True, upload_to='documentacion', verbose_name='Adjuntar CUD'),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='cud',
            field=models.BooleanField(choices=[(True, 'SI'), (False, 'NO')], default=False, verbose_name='CUD'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='fecha_vencimiento_cud',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de vencimiento CUD'),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='nro_afiliado',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='Numero de afiliado'),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='obra_social',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clasificadores.obrasocial', verbose_name='Obra social'),
        ),
    ]
