# Generated by Django 4.0.1 on 2022-10-19 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0009_beneficiario_archivo_cud_beneficiario_cud_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiario',
            name='archivo_cud',
            field=models.ImageField(blank=True, null=True, upload_to='documentacion/cud_beneficiarios', verbose_name='Adjuntar CUD'),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='nro_afiliado',
            field=models.CharField(blank=True, max_length=25, null=True, unique=True, verbose_name='Numero de afiliado'),
        ),
    ]
