# Generated by Django 4.0.1 on 2022-12-13 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clasificadores', '0004_tipobaja'),
        ('persona', '0010_alter_beneficiario_archivo_cud_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentacionbeneficiario',
            name='fecha_vencimiento',
        ),
        migrations.RemoveField(
            model_name='documentacionbeneficiario',
            name='vencimiento',
        ),
        migrations.AddField(
            model_name='documentacionbeneficiario',
            name='descripcion',
            field=models.TextField(default='Documentacion test', verbose_name='Descripción'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='archivo_cud',
            field=models.ImageField(blank=True, null=True, upload_to='beneficiarios/cud', verbose_name='Adjuntar CUD'),
        ),
        migrations.AlterField(
            model_name='documentacionbeneficiario',
            name='archivo',
            field=models.ImageField(upload_to='beneficiarios/documentacion/', verbose_name='Adjuntar documentación'),
        ),
        migrations.AlterField(
            model_name='documentacionbeneficiario',
            name='tipo_documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clasificadores.tipodocumento', verbose_name='Tipo de documento'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='apellido',
            field=models.CharField(max_length=50, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
    ]
