# Generated by Django 4.0.1 on 2022-12-13 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0012_alter_documentacionbeneficiario_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentacionbeneficiario',
            name='archivo',
            field=models.FileField(upload_to='beneficiarios/documentacion/', verbose_name='Adjuntar documentación'),
        ),
    ]
