# Generated by Django 4.0.4 on 2023-02-13 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0013_alter_documentacionbeneficiario_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='barrio',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Barrio'),
        ),
    ]
