# Generated by Django 4.0.4 on 2023-03-22 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0015_alter_persona_barrio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='cuit',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='CUIT / CUIL'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail de contacto'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
    ]
