# Generated by Django 4.0.1 on 2023-05-15 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0016_alter_persona_cuit_alter_persona_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiario',
            name='permanente',
            field=models.BooleanField(blank=True, choices=[(True, 'SI'), (False, 'NO')], max_length=2, null=True, verbose_name='¿Es permanente la discapacidad?'),
        ),
    ]
