# Generated by Django 4.0.1 on 2023-05-23 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0017_alter_beneficiario_permanente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiario',
            name='archivo_cud',
            field=models.ImageField(blank=True, null=True, upload_to='documentacion/beneficiarios/', verbose_name='Adjuntar CUD'),
        ),
        migrations.AlterField(
            model_name='documentacionbeneficiario',
            name='archivo',
            field=models.FileField(upload_to='documentacion/beneficiarios/', verbose_name='Adjuntar documentación'),
        ),
    ]
