# Generated by Django 4.0.1 on 2023-05-15 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobante',
            name='descripcion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
