# Generated by Django 4.0.1 on 2023-05-22 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0017_alter_beneficiario_permanente'),
        ('productos', '0006_alter_productobaja_options'),
        ('electrodependientes', '0016_merge_20230208_1112'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventario', '0002_alter_comprobante_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleRenovacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anterior_vencimiento', models.DateField(default=None, verbose_name='Vencimiento anterior')),
                ('nuevo_vencimiento', models.DateField(default=None, verbose_name='Nuevo vencimiento')),
                ('beneficiario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='persona.beneficiario', verbose_name='Beneficiario')),
                ('comprobante', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='inventario.comprobante', verbose_name='Nro. de Comprobante')),
                ('electro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='electrodependientes.electrodependiente', verbose_name='Electrodependiente')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto', verbose_name='Producto')),
                ('usuario_creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Detalle comprobante de renovación',
                'verbose_name_plural': 'Detalle comprobantes de renovación',
                'db_table': 'comprobante_renovacion',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='detalledevolucion',
            name='beneficiario',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to='persona.beneficiario'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='RenovacionesPrestamos',
        ),
    ]
