# Generated by Django 4.0.1 on 2023-05-22 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_detallerenovacion_detalledevolucion_beneficiario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallerenovacion',
            name='usuario_creador',
        ),
    ]
