# Generated by Django 4.0.1 on 2023-05-23 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('electrodependientes', '0016_merge_20230208_1112'),
        ('persona', '0017_alter_beneficiario_permanente'),
        ('inventario', '0004_remove_detallerenovacion_usuario_creador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleentrada',
            name='cantidad',
        ),
        migrations.AddField(
            model_name='detalledevolucion',
            name='electro',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='electrodependientes.electrodependiente'),
        ),
        migrations.AlterField(
            model_name='detalledevolucion',
            name='beneficiario',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='persona.beneficiario'),
        ),
    ]
