# Generated by Django 3.2.1 on 2022-09-27 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electrodependientes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medico',
            name='persona',
        ),
        migrations.AddField(
            model_name='medico',
            name='apellido',
            field=models.CharField(default='Ramirez', max_length=50, verbose_name='Apellidos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medico',
            name='codigo_area_c',
            field=models.CharField(default='2901', max_length=5, verbose_name='Cód. de área celular'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medico',
            name='codigo_area_f',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Cód. de área teléfono fijo'),
        ),
        migrations.AddField(
            model_name='medico',
            name='documento',
            field=models.PositiveIntegerField(default=39364857, unique=True, verbose_name='Numero de documento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medico',
            name='email',
            field=models.EmailField(default='algo@email.com', max_length=254, verbose_name='E-mail de contacto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medico',
            name='nombre',
            field=models.CharField(default='Lucia', max_length=50, verbose_name='Nombres'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medico',
            name='numero_telefono_c',
            field=models.CharField(default='5283198', max_length=7, verbose_name='Nro. de celular'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medico',
            name='numero_telefono_f',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Nro. de teléfono fijo'),
        ),
    ]
