# Generated by Django 4.0.1 on 2022-10-06 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electrodependientes', '0002_auto_20220927_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostico',
            name='tiempo_requerido',
            field=models.CharField(choices=[('6', 'Hasta 6 meses'), ('12', 'Hasta 1 año'), ('24', 'Hasta 2 años')], max_length=2, verbose_name='Tiempo estimado de requerimiento'),
        ),
    ]
