# Generated by Django 4.0.1 on 2022-10-06 14:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electrodependientes', '0003_alter_diagnostico_tiempo_requerido'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostico',
            name='fecha_finalizacion',
            field=models.DateField(default=datetime.date(2022, 10, 6), editable=False, verbose_name='Fecha de finalización'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='diagnostico',
            name='tiempo_requerido',
            field=models.CharField(choices=[('6', 'Hasta 6 meses'), ('48', 'Hasta 1 año'), ('96', 'Hasta 2 años')], max_length=2, verbose_name='Tiempo estimado de requerimiento'),
        ),
    ]
