# Generated by Django 4.0.1 on 2022-10-11 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electrodependientes', '0005_alter_diagnostico_tiempo_requerido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='titulardesuministro',
            old_name='titular_servicio',
            new_name='titularServicio',
        ),
    ]
