# Generated by Django 4.0.1 on 2022-10-19 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electrodependientes', '0006_rename_titular_servicio_titulardesuministro_titularservicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostico',
            name='historia_clinica',
            field=models.TextField(blank=True, null=True, verbose_name='Resumen detallado de la historia clínica'),
        ),
    ]
