# Generated by Django 4.0.1 on 2022-10-20 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electrodependientes', '0007_alter_diagnostico_historia_clinica'),
    ]

    operations = [
        migrations.AddField(
            model_name='electrodependiente',
            name='archivo_formulario',
            field=models.ImageField(blank=True, null=True, upload_to='documentacion/electros/', verbose_name='Adjuntar Formulario de registro'),
        ),
    ]
