# Generated by Django 4.0.4 on 2022-12-22 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electrodependientes', '0010_titulardesuministro_activo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='codigo_area_c',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Cód. de área celular'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='numero_telefono_c',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Nro. de celular'),
        ),
    ]
