# Generated by Django 4.0.4 on 2023-01-25 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electrodependientes', '0011_electrodependiente_anio_expediente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electrodependiente',
            name='anio_expediente',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Expediente año'),
        ),
        migrations.AlterField(
            model_name='electrodependiente',
            name='letra_expediente',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Expediente letra'),
        ),
        migrations.AlterField(
            model_name='electrodependiente',
            name='nro_expediente',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Expediente número'),
        ),
    ]
