# Generated by Django 4.0.4 on 2023-01-25 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electrodependientes', '0012_alter_electrodependiente_anio_expediente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='electrodependiente',
            name='documentacion',
            field=models.FileField(blank=True, null=True, upload_to='documentacion/electrodependientes/', verbose_name='Adjuntar documentación (Max. 5 archivos)'),
        ),
    ]
