# Generated by Django 4.0.4 on 2023-01-27 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('electrodependientes', '0013_electrodependiente_documentacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electrodependiente',
            name='archivo_formulario',
        ),
        migrations.RemoveField(
            model_name='electrodependiente',
            name='documentacion',
        ),
        migrations.CreateModel(
            name='DocumentacionElectro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documentacion', models.FileField(blank=True, null=True, upload_to='documentacion/electrodependientes/', verbose_name='Adjuntar documentación (Max. 5 archivos)')),
                ('formulario', models.FileField(blank=True, null=True, upload_to='documentacion/electrodependientes/', verbose_name='Adjuntar Formulario físico')),
                ('electrodependiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electrodependientes.electrodependiente', verbose_name='Electrodependiente')),
            ],
            options={
                'verbose_name': 'Documentacion electrodependiente',
                'verbose_name_plural': 'Documentacion electrodependientes',
                'db_table': 'electrodependiente_docs',
                'ordering': ['id'],
            },
        ),
    ]
