# Generated by Django 4.0.4 on 2023-01-27 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electrodependientes', '0014_remove_electrodependiente_archivo_formulario_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='documentacionelectro',
            table='documentacion_electro',
        ),
    ]
