# Generated by Django 4.0.4 on 2023-02-08 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electrodependientes', '0011_alter_medico_codigo_area_c_and_more'),
        ('electrodependientes', '0015_alter_documentacionelectro_table'),
    ]

    operations = [
    ]
